export const MOCK = {
  meta: {
    period_label: 'Jan 6 – Feb 4, 2026',
    date_from: '2026-01-06',
    date_to:   '2026-02-04',
  },

  available_filters: {
    carriers: [
      { code: 'nacex',                 name: 'Nacex'                 },
      { code: 'dhl',                   name: 'DHL'                   },
      { code: 'dpd-poland',            name: 'DPD Poland'            },
      { code: 'portugal-post',         name: 'Portugal Post'         },
      { code: 'acs-courier',           name: 'ACS Courier'           },
      { code: 'inpost-poland',         name: 'InPost Poland'         },
      { code: 'packeta',               name: 'Packeta'               },
      { code: 'dpd',                   name: 'DPD'                   },
      { code: 'fan-courier',           name: 'FAN Courier'           },
      { code: 'econt',                 name: 'Econt'                 },
      { code: 'brt-italy',             name: 'BRT Italy'             },
      { code: 'slovak-parcel-service', name: 'Slovak Parcel Service' },
      { code: 'ups',                   name: 'UPS'                   },
      { code: 'hermes-uk',             name: 'Hermes UK'             },
      { code: 'elta-courier-greece',   name: 'ELTA Courier Greece'   },
    ],
    origins: [
      { code: 'ES', name: 'Spain'    }, { code: 'SK', name: 'Slovakia' },
      { code: 'PL', name: 'Poland'   }, { code: 'GR', name: 'Greece'   },
      { code: 'RO', name: 'Romania'  }, { code: 'DE', name: 'Germany'  },
      { code: 'IT', name: 'Italy'    }, { code: 'CY', name: 'Cyprus'   },
    ],
    destinations: [
      { code: 'ES', name: 'Spain'          }, { code: 'DE', name: 'Germany'        },
      { code: 'PT', name: 'Portugal'       }, { code: 'PL', name: 'Poland'         },
      { code: 'GR', name: 'Greece'         }, { code: 'BG', name: 'Bulgaria'       },
      { code: 'LT', name: 'Lithuania'      }, { code: 'SI', name: 'Slovenia'       },
      { code: 'GB', name: 'United Kingdom' }, { code: 'RO', name: 'Romania'        },
    ],
  },

  overview: {
    kpis: {
      total_shipments:     100000,
      pending_count:       512,
      pending_pct:         0.5,
      delivered_count:     65994,
      delivery_rate_pct:   66.6,
      resolution_rate_pct: 98.0,
      active_count:        1978,
      median_transit_days: 2.0,
      edd_on_time_pct:     62.6,
      edd_shipments_count: 15884,
    },
    daily_volume: [
      { date: '2026-01-06', count: 2186,  is_weekend: false, rolling7_avg: 2186.0 },
      { date: '2026-01-07', count: 4615,  is_weekend: false, rolling7_avg: 3400.5 },
      { date: '2026-01-08', count: 3831,  is_weekend: false, rolling7_avg: 3544.0 },
      { date: '2026-01-09', count: 3546,  is_weekend: false, rolling7_avg: 3544.5 },
      { date: '2026-01-10', count: 1534,  is_weekend: false, rolling7_avg: 3142.4 },
      { date: '2026-01-11', count: 1346,  is_weekend: true,  rolling7_avg: 2843.0 },
      { date: '2026-01-12', count: 6323,  is_weekend: true,  rolling7_avg: 3340.1 },
      { date: '2026-01-13', count: 3278,  is_weekend: false, rolling7_avg: 3496.1 },
      { date: '2026-01-14', count: 3365,  is_weekend: false, rolling7_avg: 3318.9 },
      { date: '2026-01-15', count: 2991,  is_weekend: false, rolling7_avg: 3197.6 },
      { date: '2026-01-16', count: 2942,  is_weekend: false, rolling7_avg: 3077.0 },
      { date: '2026-01-17', count: 1208,  is_weekend: false, rolling7_avg: 3064.7 },
      { date: '2026-01-18', count: 1686,  is_weekend: true,  rolling7_avg: 3113.3 },
      { date: '2026-01-19', count: 5388,  is_weekend: true,  rolling7_avg: 3008.3 },
      { date: '2026-01-20', count: 2791,  is_weekend: false, rolling7_avg: 2910.1 },
      { date: '2026-01-21', count: 2789,  is_weekend: false, rolling7_avg: 2828.4 },
      { date: '2026-01-22', count: 3090,  is_weekend: false, rolling7_avg: 2841.6 },
      { date: '2026-01-23', count: 3061,  is_weekend: false, rolling7_avg: 2859.0 },
      { date: '2026-01-24', count: 1070,  is_weekend: false, rolling7_avg: 2839.3 },
      { date: '2026-01-25', count: 1538,  is_weekend: true,  rolling7_avg: 2818.1 },
      { date: '2026-01-26', count: 5471,  is_weekend: true,  rolling7_avg: 2830.0 },
      { date: '2026-01-27', count: 2858,  is_weekend: false, rolling7_avg: 2839.6 },
      { date: '2026-01-28', count: 2637,  is_weekend: false, rolling7_avg: 2818.0 },
      { date: '2026-01-29', count: 2535,  is_weekend: false, rolling7_avg: 2737.1 },
      { date: '2026-01-30', count: 2515,  is_weekend: false, rolling7_avg: 2660.6 },
      { date: '2026-01-31', count: 916,   is_weekend: false, rolling7_avg: 2638.0 },
      { date: '2026-02-01', count: 1342,  is_weekend: true,  rolling7_avg: 2610.6 },
      { date: '2026-02-02', count: 4818,  is_weekend: true,  rolling7_avg: 2516.7 },
      { date: '2026-02-03', count: 3031,  is_weekend: false, rolling7_avg: 2627.7 },
      { date: '2026-02-04', count: 1503,  is_weekend: false, rolling7_avg: 2379.7 },
    ],
    volume_trend: { last7_avg: 2380, prev7_avg: 2818, trend_pct: -15.5 },
    active_by_status: [
      { status: 'info_received',        label: 'Info Received',        count: 1416, color: '#8b5cf6' },
      { status: 'in_transit',           label: 'In Transit',           count: 355,  color: '#3b82f6' },
      { status: 'available_for_pickup', label: 'Available for Pickup', count: 149,  color: '#f97316' },
      { status: 'out_for_delivery',     label: 'Out for Delivery',     count: 29,   color: '#14b8a6' },
      { status: 'failed_attempt',       label: 'Failed Attempt',       count: 29,   color: '#ef4444' },
    ],
  },

  carriers: {
    kpis: {
      most_used:          { carrier: 'Nacex',     shipments: 37706 },
      best_delivery_rate: { carrier: 'Hermes UK', rate_pct: 99.7  },
      fastest:            { carrier: 'Hermes UK', avg_transit_days: 1.2 },
      top_rated:          { carrier: 'Hermes UK', stars_raw: 4.6, stars_str: '★★★★½' },
    },
    scorecard: [
      { carrier: 'Hermes UK',            shipments:  643,   delivery_rate_pct: 99.7, exception_rate_pct:  0.0, avg_transit_days: 1.2, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 4.6, stars_str: '★★★★½', score: 0.92 },
      { carrier: 'UPS',                  shipments:  230,   delivery_rate_pct: 91.7, exception_rate_pct:  5.7, avg_transit_days: 3.6, edd_on_time_pct:  91.0,edd_shipments:  230, stars_raw: 4.3, stars_str: '★★★★☆', score: 0.86 },
      { carrier: 'DPD Poland',           shipments: 13217,  delivery_rate_pct: 79.2, exception_rate_pct: 10.1, avg_transit_days: 2.8, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.8, stars_str: '★★★½☆', score: 0.76 },
      { carrier: 'Slovak Parcel Service',shipments:  586,   delivery_rate_pct: 82.7, exception_rate_pct: 10.0, avg_transit_days: 3.5, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.7, stars_str: '★★★½☆', score: 0.74 },
      { carrier: 'FAN Courier',          shipments: 1284,   delivery_rate_pct: 70.2, exception_rate_pct: 29.8, avg_transit_days: 1.5, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.6, stars_str: '★★★½☆', score: 0.72 },
      { carrier: 'InPost Poland',        shipments: 2106,   delivery_rate_pct: 66.8, exception_rate_pct: 31.0, avg_transit_days: 1.3, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.6, stars_str: '★★★½☆', score: 0.72 },
      { carrier: 'Nacex',                shipments: 37706,  delivery_rate_pct: 62.1, exception_rate_pct: 37.7, avg_transit_days: 2.3, edd_on_time_pct: 100.0,edd_shipments: 10245,stars_raw: 3.6, stars_str: '★★★½☆', score: 0.72 },
      { carrier: 'Econt',                shipments: 1820,   delivery_rate_pct: 67.5, exception_rate_pct: 32.5, avg_transit_days: 1.8, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.5, stars_str: '★★★½☆', score: 0.70 },
      { carrier: 'DHL',                  shipments: 22058,  delivery_rate_pct: 68.0, exception_rate_pct: 31.4, avg_transit_days: 2.7, edd_on_time_pct:  56.0,edd_shipments: 5639, stars_raw: 3.4, stars_str: '★★★☆☆', score: 0.68 },
      { carrier: 'ACS Courier',          shipments: 6251,   delivery_rate_pct: 65.7, exception_rate_pct: 34.2, avg_transit_days: 3.5, edd_on_time_pct:  79.0,edd_shipments:  148, stars_raw: 3.3, stars_str: '★★★☆☆', score: 0.66 },
      { carrier: 'BRT Italy',            shipments: 1540,   delivery_rate_pct: 65.7, exception_rate_pct: 33.7, avg_transit_days: 2.3, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.3, stars_str: '★★★☆☆', score: 0.66 },
      { carrier: 'Packeta',              shipments: 2255,   delivery_rate_pct: 75.2, exception_rate_pct: 24.7, avg_transit_days: 5.0, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.1, stars_str: '★★★☆☆', score: 0.62 },
      { carrier: 'DPD',                  shipments: 3410,   delivery_rate_pct: 59.5, exception_rate_pct: 30.5, avg_transit_days: 3.3, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.1, stars_str: '★★★☆☆', score: 0.62 },
      { carrier: 'Portugal Post',        shipments: 8854,   delivery_rate_pct: 59.0, exception_rate_pct: 40.3, avg_transit_days: 2.6, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 3.0, stars_str: '★★★☆☆', score: 0.60 },
      { carrier: 'ELTA Courier Greece',  shipments:  169,   delivery_rate_pct: 53.8, exception_rate_pct:  7.7, avg_transit_days: 6.8, edd_on_time_pct: null, edd_shipments: null,  stars_raw: 2.6, stars_str: '★★½☆☆', score: 0.52 },
    ],
  },

  geography: {
    top_origin_countries: [
      { country_code: 'ES', country_name: 'Spain',    shipments: 46560 },
      { country_code: 'SK', country_name: 'Slovakia', shipments: 23197 },
      { country_code: 'PL', country_name: 'Poland',   shipments: 13937 },
      { country_code: 'GR', country_name: 'Greece',   shipments:  5524 },
      { country_code: 'RO', country_name: 'Romania',  shipments:  4735 },
      { country_code: 'DE', country_name: 'Germany',  shipments:  3338 },
      { country_code: 'IT', country_name: 'Italy',    shipments:  1034 },
      { country_code: 'CY', country_name: 'Cyprus',   shipments:   896 },
    ],
    top_destination_countries: [
      { country_code: 'ES', country_name: 'Spain',          shipments: 32511 },
      { country_code: 'DE', country_name: 'Germany',        shipments: 24846 },
      { country_code: 'PT', country_name: 'Portugal',       shipments: 14124 },
      { country_code: 'PL', country_name: 'Poland',         shipments:  5684 },
      { country_code: 'GR', country_name: 'Greece',         shipments:  5534 },
      { country_code: 'BG', country_name: 'Bulgaria',       shipments:  4593 },
      { country_code: 'LT', country_name: 'Lithuania',      shipments:  3746 },
      { country_code: 'SI', country_name: 'Slovenia',       shipments:  1823 },
    ],
    avg_delivery_time_by_destination: [
      { country_code: 'GB', country_name: 'United Kingdom', avg_transit_days: 1.2 },
      { country_code: 'RO', country_name: 'Romania',        avg_transit_days: 1.7 },
      { country_code: 'PL', country_name: 'Poland',         avg_transit_days: 1.7 },
      { country_code: 'BG', country_name: 'Bulgaria',       avg_transit_days: 1.8 },
      { country_code: 'SK', country_name: 'Slovakia',       avg_transit_days: 2.0 },
      { country_code: 'ES', country_name: 'Spain',          avg_transit_days: 2.3 },
      { country_code: 'CZ', country_name: 'Czech Republic', avg_transit_days: 2.4 },
      { country_code: 'PT', country_name: 'Portugal',       avg_transit_days: 2.5 },
      { country_code: 'DE', country_name: 'Germany',        avg_transit_days: 2.7 },
      { country_code: 'HU', country_name: 'Hungary',        avg_transit_days: 2.9 },
    ],
    destination_keys: ['ES', 'DE', 'PT', 'PL', 'GR', 'BG', 'GB'],
    carrier_performance_by_destination: {
      ES: { country_name: 'Spain', carriers: [
        { carrier: 'Nacex',     shipments: 28540, delivery_rate_pct:  63.1, avg_transit_days: 2.3, exception_rate_pct: 36.7 },
        { carrier: 'DHL',       shipments:  3210, delivery_rate_pct:  90.9, avg_transit_days: 2.7, exception_rate_pct:  9.1 },
        { carrier: 'DPD Poland',shipments:   761, delivery_rate_pct: 100.0, avg_transit_days: 2.8, exception_rate_pct:  0.0 },
      ]},
      DE: { country_name: 'Germany', carriers: [
        { carrier: 'Slovak Parcel Service',shipments: 19053, delivery_rate_pct: 79.4, avg_transit_days: 2.8, exception_rate_pct: 10.2 },
        { carrier: 'DPD Poland',           shipments:  3101, delivery_rate_pct: 82.3, avg_transit_days: 2.9, exception_rate_pct:  9.4 },
        { carrier: 'DHL',                  shipments:  2692, delivery_rate_pct: 71.0, avg_transit_days: 3.1, exception_rate_pct: 22.4 },
      ]},
      PT: { country_name: 'Portugal', carriers: [
        { carrier: 'Portugal Post',shipments: 8854, delivery_rate_pct: 59.0, avg_transit_days: 2.6, exception_rate_pct: 40.3 },
        { carrier: 'Nacex',        shipments: 5250, delivery_rate_pct: 60.8, avg_transit_days: 2.4, exception_rate_pct: 39.1 },
      ]},
      PL: { country_name: 'Poland', carriers: [
        { carrier: 'InPost Poland',shipments: 2106, delivery_rate_pct: 66.8, avg_transit_days: 1.3, exception_rate_pct: 31.0 },
        { carrier: 'DPD Poland',   shipments: 1982, delivery_rate_pct: 83.1, avg_transit_days: 1.8, exception_rate_pct:  8.4 },
        { carrier: 'Packeta',      shipments: 1596, delivery_rate_pct: 75.2, avg_transit_days: 2.1, exception_rate_pct: 24.7 },
      ]},
      GR: { country_name: 'Greece', carriers: [
        { carrier: 'ELTA Courier Greece',shipments: 3821, delivery_rate_pct: 53.8, avg_transit_days: 6.8, exception_rate_pct:  7.7 },
        { carrier: 'ACS Courier',        shipments: 1713, delivery_rate_pct: 65.7, avg_transit_days: 3.5, exception_rate_pct: 34.2 },
      ]},
      BG: { country_name: 'Bulgaria', carriers: [
        { carrier: 'Econt',      shipments: 1820, delivery_rate_pct: 67.5, avg_transit_days: 1.8, exception_rate_pct: 32.5 },
        { carrier: 'FAN Courier',shipments: 1284, delivery_rate_pct: 70.2, avg_transit_days: 1.5, exception_rate_pct: 29.8 },
      ]},
      GB: { country_name: 'United Kingdom', carriers: [
        { carrier: 'Hermes UK',shipments: 643, delivery_rate_pct: 99.7, avg_transit_days: 1.2, exception_rate_pct: 0.0 },
      ]},
    } as Record<string, { country_name: string; carriers: Array<{ carrier: string; shipments: number; delivery_rate_pct: number; avg_transit_days: number; exception_rate_pct: number }> }>,
    top_routes: [
      { route_label: 'Spain → Spain',      shipments: 32456, delivery_rate_pct: 63.1, exception_rate_pct: 36.7, avg_transit_days: 2.3 },
      { route_label: 'Slovakia → Germany', shipments: 19053, delivery_rate_pct: 79.4, exception_rate_pct: 10.2, avg_transit_days: 2.8 },
      { route_label: 'Spain → Portugal',   shipments: 14104, delivery_rate_pct: 59.1, exception_rate_pct: 40.3, avg_transit_days: 2.5 },
      { route_label: 'Greece → Greece',    shipments:  5524, delivery_rate_pct: 53.9, exception_rate_pct:  7.7, avg_transit_days: 6.8 },
      { route_label: 'Poland → Poland',    shipments:  4870, delivery_rate_pct: 77.8, exception_rate_pct: 11.2, avg_transit_days: 1.7 },
      { route_label: 'Romania → Bulgaria', shipments:  4472, delivery_rate_pct: 68.4, exception_rate_pct: 31.5, avg_transit_days: 1.8 },
      { route_label: 'Poland → Lithuania', shipments:  3746, delivery_rate_pct: 78.2, exception_rate_pct: 10.3, avg_transit_days: 1.7 },
      { route_label: 'Poland → Germany',   shipments:  3101, delivery_rate_pct: 82.3, exception_rate_pct:  9.4, avg_transit_days: 2.9 },
      { route_label: 'Spain → Germany',    shipments:  2692, delivery_rate_pct: 71.0, exception_rate_pct: 22.4, avg_transit_days: 3.1 },
      { route_label: 'Germany → Germany',  shipments:  2140, delivery_rate_pct: 74.3, exception_rate_pct: 18.2, avg_transit_days: 2.4 },
    ],
  },

  delivery_speed: {
    kpis: {
      avg_transit_days:    2.8,
      median_transit_days: 2.0,
      p10_transit_days:    0.5,
      p90_transit_days:    6.9,
    },
    histogram: [
      { bucket_label: '0–1d',   count:  9820 }, { bucket_label: '1–2d',   count: 18640 },
      { bucket_label: '2–3d',   count: 14830 }, { bucket_label: '3–4d',   count:  9210 },
      { bucket_label: '4–5d',   count:  5380 }, { bucket_label: '5–6d',   count:  3520 },
      { bucket_label: '6–7d',   count:  2410 }, { bucket_label: '7–8d',   count:  1290 },
      { bucket_label: '8–9d',   count:   680 }, { bucket_label: '9–10d',  count:   521 },
      { bucket_label: '10–12d', count:   820 }, { bucket_label: '12–15d', count:   590 },
      { bucket_label: '> 15d',  count:   285 },
    ],
    speed_categories: [
      { label: '< 2 days',  count: 28460, color: '#22c55e' },
      { label: '2–5 days',  count: 29420, color: '#3b82f6' },
      { label: '5–10 days', count:  8421, color: '#f97316' },
      { label: '> 10 days', count:  1695, color: '#ef4444' },
    ],
    avg_transit_by_carrier: [
      { carrier: 'Hermes UK',            avg_transit_days: 1.2 },
      { carrier: 'InPost Poland',        avg_transit_days: 1.3 },
      { carrier: 'FAN Courier',          avg_transit_days: 1.5 },
      { carrier: 'Econt',                avg_transit_days: 1.8 },
      { carrier: 'Nacex',                avg_transit_days: 2.3 },
      { carrier: 'BRT Italy',            avg_transit_days: 2.3 },
      { carrier: 'Portugal Post',        avg_transit_days: 2.6 },
      { carrier: 'DHL',                  avg_transit_days: 2.7 },
      { carrier: 'DPD Poland',           avg_transit_days: 2.8 },
      { carrier: 'DPD',                  avg_transit_days: 3.3 },
      { carrier: 'ACS Courier',          avg_transit_days: 3.5 },
      { carrier: 'Slovak Parcel Service',avg_transit_days: 3.5 },
      { carrier: 'UPS',                  avg_transit_days: 3.6 },
      { carrier: 'Packeta',              avg_transit_days: 5.0 },
      { carrier: 'ELTA Courier Greece',  avg_transit_days: 6.8 },
    ],
  },

  issues: {
    kpis: {
      overall_issue_rate_pct: 33.4,
      affected_shipments:     32882,
      carrier_fewest: { carrier: 'Hermes UK',     exception_rate_pct: 0.0  },
      carrier_most:   { carrier: 'Portugal Post', exception_rate_pct: 40.3 },
    },
    issue_rate_over_time: [
      { date: '2026-01-06', issue_rate_pct: 31.2 }, { date: '2026-01-07', issue_rate_pct: 34.8 },
      { date: '2026-01-08', issue_rate_pct: 33.1 }, { date: '2026-01-09', issue_rate_pct: 35.6 },
      { date: '2026-01-10', issue_rate_pct: 29.4 }, { date: '2026-01-11', issue_rate_pct: 30.2 },
      { date: '2026-01-12', issue_rate_pct: 36.7 }, { date: '2026-01-13', issue_rate_pct: 34.1 },
      { date: '2026-01-14', issue_rate_pct: 32.8 }, { date: '2026-01-15', issue_rate_pct: 31.9 },
      { date: '2026-01-16', issue_rate_pct: 35.3 }, { date: '2026-01-17', issue_rate_pct: 33.7 },
      { date: '2026-01-18', issue_rate_pct: 30.5 }, { date: '2026-01-19', issue_rate_pct: 37.2 },
      { date: '2026-01-20', issue_rate_pct: 34.9 }, { date: '2026-01-21', issue_rate_pct: 32.3 },
      { date: '2026-01-22', issue_rate_pct: 33.8 }, { date: '2026-01-23', issue_rate_pct: 35.1 },
      { date: '2026-01-24', issue_rate_pct: 28.9 }, { date: '2026-01-25', issue_rate_pct: 31.4 },
      { date: '2026-01-26', issue_rate_pct: 36.8 }, { date: '2026-01-27', issue_rate_pct: 34.2 },
      { date: '2026-01-28', issue_rate_pct: 33.5 }, { date: '2026-01-29', issue_rate_pct: 32.1 },
      { date: '2026-01-30', issue_rate_pct: 34.6 }, { date: '2026-01-31', issue_rate_pct: 30.8 },
      { date: '2026-02-01', issue_rate_pct: 29.7 }, { date: '2026-02-02', issue_rate_pct: 37.9 },
      { date: '2026-02-03', issue_rate_pct: 35.4 }, { date: '2026-02-04', issue_rate_pct: 33.1 },
    ],
    exception_rate_by_carrier: [
      { carrier: 'Portugal Post',         exception_rate_pct: 40.3 },
      { carrier: 'Nacex',                 exception_rate_pct: 37.7 },
      { carrier: 'ACS Courier',           exception_rate_pct: 34.2 },
      { carrier: 'BRT Italy',             exception_rate_pct: 33.7 },
      { carrier: 'Econt',                 exception_rate_pct: 32.5 },
      { carrier: 'DHL',                   exception_rate_pct: 31.4 },
      { carrier: 'InPost Poland',         exception_rate_pct: 31.0 },
      { carrier: 'DPD',                   exception_rate_pct: 30.5 },
      { carrier: 'FAN Courier',           exception_rate_pct: 29.8 },
      { carrier: 'Packeta',               exception_rate_pct: 24.7 },
      { carrier: 'DPD Poland',            exception_rate_pct: 10.1 },
      { carrier: 'Slovak Parcel Service', exception_rate_pct: 10.0 },
      { carrier: 'ELTA Courier Greece',   exception_rate_pct:  7.7 },
      { carrier: 'UPS',                   exception_rate_pct:  5.7 },
      { carrier: 'Hermes UK',             exception_rate_pct:  0.0 },
    ],
  },
};
